config/routes.rb
Rails.application.routes.draw do
	root "articles#index"
	
	resources :articles do
		resources :comments
	end

	resources :tags

	resources :authors
	
	resources :author_sessions, only: [ :new, :create, :destroy ]

	get 'login' => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end

	validates :title, :body,
				presence: true
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password

    validates :username, presence: true, uniqueness: true, length: { maximum: 11 }
    validates :password, length: { minimum: 4 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :author_name, :body,
  			presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings

	validates :name,
				presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_filter :require_login, only: [:edit, :update]
	before_action :find_article, only: [:show, :edit, :update, :destroy]

	def index
		@articles = Article.all
	end

	def show
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		if params[:tag].present?
			@article = Article.new(tag_list: params[:tag])
		else
			@article = Article.new
		end
	end

	def edit
		
	end

	def create
		@article = Article.create(article_params)

		if @article.save
			flash.notice = "'#{@article.title}' was created!"
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article.update(article_params)

		flash.notice = "'#{@article.title}' has been updated."

		redirect_to article_path(@article)
	end

	def destroy
		@article.destroy

		flash.notice = "'#{@article.title}' has been deleted."

		redirect_to articles_path
	end

	private

	def find_article
		@article = Article.find(params[:id])
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new
		
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
		else
			flash.now.alert = "Login failed."
			render action: :new
		end	
	end

	def destroy
		logout
		redirect_to(:authors, notice: 'Logged out.')
	end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path, notice: "You are not authorized to do that."
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	include CommentsHelper
	before_filter :require_login, except: [:create]

	def create
		@comment = Comment.create(comment_params)
		@comment.article_id = params[:article_id]

		if @comment.save
			redirect_to article_path(@comment.article)
		else
			flash.notice = "Uh oh. Your comment didn't save, try again."
			redirect_to article_path(@comment.article)
		end
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	include TagsHelper
	before_filter :require_login, only: [:destroy]

	before_action :find_tag, only: [:show, :destroy]

	def index
		@tags = Tag.all
	end

	def show
		
	end

	def destroy
		@tag.destroy

		flash.notice = "The '#{@tag.name}' tag has been deleted."

		redirect_to tags_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/helpers/tags_helper.rb
module TagsHelper
	def find_tag
		@tag = Tag.find(params[:id])
	end
end

app/views/articles/_back.html.erb
<div id="back">
	<%= link_to 'back', articles_path, class: "back" %>
</div>

app/views/articles/_comment.html.erb
<div class="comment">
	<h4><span class="author_name"><%= comment.author_name.upcase %></span><span id="says"> says...</span></h4>
	
	<p><%= comment.body %></p>
	
	<p class="later">
		<%= distance_of_time_in_words(comment.created_at, Time.now) %> ago</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
	
	<% if @article.errors.present? %>
		<ul>
			<% @article.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	<% end %>

		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.label :tag %><br>
			<%= f.text_field :tag_list %>
		</p>

		<p>
			<%= f.label :image, "Attach a New Image" %><br>
			<%= f.file_field :image %>
		</p>

		<p>
			<%= f.submit %>
		</p>
<% end %>

app/views/articles/_image.html.erb
<% if  @article.image.exists? %>
	<div class="image_container">
		<%= image_tag @article.image.url, class: "image" %>
	</div>
<% end %>

app/views/articles/_list.html.erb
<ul>
	<% @articles.each do |article| %>	
		<div class="line"></div>
		<li class="content_list_item">

			<%= link_to article.title, article_path(article),
				class: 'article_title',
				id: "article_#{article.id}" %><br>
				
				<% if logged_in? %>
					<%= link_to "edit", edit_article_path(article),
								class: "article_UD" %>
					<span id="vertical"> | </span>
					<%= link_to "delete", article_path(article),
								method: :delete,
								data: { confirm: "Are you sure?" },
								class: "article_UD" %>
				<% end %>
		</li>
		<div class="line"></div>
	<% end %>
</ul>

app/views/articles/_new_article_link.html.erb
<%= link_to "new article", new_article_path, class: "nav_buttons", id: "nav_new_article" %>

app/views/articles/_tags.html.erb
<p class="tags">
	<% if @article.tags.count > 1 %>
		
		<% @article.tags.each do |tag| %>
			
			<%= link_to tag.name.upcase, tag_path(tag, article_id: @article.id) %>
			<% if tag != @article.tags.last %>
				<span class="ampersand">&</span>
			<% end %>
		<% end %>
	
	<% elsif @article.tags.count == 1 %>
		
		<% tag = @article.tags.first %>
		<%= link_to tag.name.upcase, tag_path(tag, article_id: @article.id) %>
	
	<% end %>
</p>

app/views/articles/edit.html.erb
<h1>EDIT</h1>

<%= render 'form' %>

<%= render 'back' %>

app/views/articles/index.html.erb
<h1>PÚBLICO</h1>

<%= render 'list' %>


<%= render 'new_article_link' %>
<%= link_to "view all tags", tags_path, class: "nav_buttons"  %>

app/views/articles/new.html.erb
<h1>CREATE A NEW ARTICLE</h1>
<%= render 'form' %>

<% if params[:tag].present? %>
	<div id="back">
		<%= link_to 'back', tag_path(params[:tag_id]), class: 'back' %>
	</div>
<% else %>
	<%= render 'back' %>	
<% end %>

app/views/articles/show.html.erb
<h1>
	<%= @article.title.upcase %>
</h1>

<%= render 'image' %>
<div class="article_body">
	<p><%= @article.body %></p>
</div>

<%= render 'tags' %>

<%= render 'back' %>

<div id="comments">
	<%= render partial: '/articles/comment', collection: @article.comments %>
</div>

<%= render partial: 'comments/form' %>

app/views/author_sessions/new.html.erb
<h1>LOGIN</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
  	<%= label_tag :email %>
  	<%= text_field_tag :email %>
  	<br>
  </div>

  <div class="field">
  	<%= label_tag :password %>
  	<%= password_field_tag :password %>
  	<br>
  </div>

  <div class="actions">
  	<%= submit_tag "Login" %>
  </div>
<% end -%>

<%= render 'articles/back' %>

<style type="text/css">
  .login_status, #outer_circle {display: none;}
</style>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>EDIT</h1>

<%= render 'form' %>

<%= link_to 'back', authors_path, class:"back" %>
<%= link_to 'show', @author, class:"back" %>

<style type="text/css">
	.field {
		text-align: center;
		margin-bottom: 20px;
	}
</style>

app/views/authors/index.html.erb
<h1>USER</h1>

<table>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to "#{author.username}", author_path(author) %></td>
        <td><i><%= mail_to(author.email) %></i></td>
        <td class="author_functions"><%= link_to 'edit', edit_author_path(author), class:"back" %></td>
        <td class="author_functions"><%= link_to 'destroy', author, method: :delete, class:"back",data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "view all articles", articles_path, class: "nav_buttons" %>
<%= link_to 'new user', new_author_path, class: "nav_buttons", id: "nav_new_article" %>
<%= link_to "view all tags", tags_path, class: "nav_buttons" %>

app/views/authors/new.html.erb
<h1>NEW USER</h1>

<%= render 'form' %>

<%= link_to 'back', authors_path, class:"back" %>

<style type="text/css">
	.field {
		text-align: center;
		margin-bottom: 20px;
	}
</style>

app/views/authors/show.html.erb
<h1>
  <%= @author.username.upcase %>
</h1>

<p>
  <%= @author.email %>
</p>

<p>
	Created on <%= @author.created_at.to_date %>
</p>

<%= link_to 'back', authors_path, class:"back" %>
<%= link_to 'edit', edit_author_path(@author), class: "back" %>

app/views/comments/_form.html.erb
<h3>POST A COMMENT</h3>

<div id="comment_form">
	<%= form_for [ @article, @comment ] do |f| %>
		<p>
			<%= f.label :author_name, "Your name" %><br>
			<%= f.text_field :author_name %>
		</p>

		<p>
			<%= f.label :body, "Your comment" %><br>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.submit 'Submit' %>
		</p>
	<% end %>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
	<p class="flash">
		<%= flash.notice %>
	</p>
<% end %>

app/views/layouts/_login_status.html.erb
<p class="login_status">
	<% if logged_in? %>
		<%= link_to "#{current_user.username.downcase}", author_path(current_user.id), class: "username" %>
		<div id="outer_circle"></div>
		<%= link_to "logout", logout_path, class: "logout" %>
	<% else %>
		<%= link_to "login", login_path, class: "login" %>
		<div id="outer_circle"></div>
	<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	<title>PÚBLICO | Blogosquare</title>
 	<!-- FOR "main.css": -->
	<!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,700,300' rel='stylesheet' type='text/css'> -->
	<!-- FOR "new_main.css": -->
	<link href='http://fonts.googleapis.com/css?family=Gentium+Book+Basic:400italic,400|Open+Sans:800' rel='stylesheet' type='text/css'>

	<%= favicon_link_tag %>

 	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

 	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

 	<%= csrf_meta_tags %>
</head>

<body>
	
	<%= render 'layouts/flash' %>

	<div id="container">
		
		<div id="content">
			
			<%= yield %>
		
		</div>
	</div>
	
	<%= render 'layouts/login_status' %>
</body>
</html>

app/views/tags/_list.html.erb
<ul>
	<% @tags.sort_by(&:name).each do |tag| %>	
		<div class="line"></div>
		<li class="content_list_item">
			<%= link_to tag.name.capitalize, tag_path(tag, i: 1),
				class: 'article_title',
				id: "tag_#{tag.id}" %><br>
				
				<% if logged_in? %>
				<%= link_to "delete", tag_path(tag),
							method: :delete,
							data: { confirm: "Are you sure?" },
							class: "article_UD" %>
				<% end %>
		</li>
		<div class="line"></div>
	<% end %>
</ul>

app/views/tags/index.html.erb
<h1>ALL TAGS</h1>


<%= render 'list' %>


<%= render partial: '/articles/new_article_link' %>
<%= link_to "view articles", articles_path, class: "nav_buttons"  %>

app/views/tags/show.html.erb
<h1><%= @tag.name.upcase %></h1>

	<ul>
		<% if @tag.articles.count == 0 %>
			<li>Sorry, there aren't any articles with this tag.</li>
		<% end %>	

		<% @tag.articles.sort_by(&:title).each do |article| %>
		<div class="line"></div>
			<li>
				<%= link_to article.title, article_path(article)  %>
			</li>
		<div class="line"></div>
		<% end %>
	</ul>

<div id="back">

	<% if params[:article_id].present? %>
		<%= link_to "back", article_path(params[:article_id]), class: "back" %>
	<% else %>
		<%= link_to "back", tags_path, class: "back" %>
	<% end %>
</div>

<%= link_to "view all articles", articles_path, class: "nav_buttons" %>
<%= link_to "new article", new_article_path(tag: @tag.name, tag_id: @tag.id), class: "nav_buttons", id: "nav_new_article" %>
<%= link_to "view all tags", tags_path, class: "nav_buttons" %>

<style type="text/css">
	#back {border-top: 1px solid transparent; margin-bottom: 5%;}
</style>